### ISSUE TITLE
Create metrics abstraction

### ISSUE THREAD

**Issue by alan-cooney** [ai-safety-foundation/sparse_autoencoder#33]
We should have some sort of abstract metrics class (or similar) to standardise the approach for adding metrics to the pipeline.

**Comment by HoagyC** [comment]
Have started to think about/work on this.
Basic idea is
-  Have a `Metric` class in train/metrics/metric_class.py  
- `Metric` implements `compute_and_log` which takes in a TypedDict of all of the relevant info from train loop
- Think we should computing and logging together because potential outputs may be very different or only run every `n` steps, though could keep separate if wanted
- Document that Metrics are allowed to retain state between calls as is necessary for things like feature_density
- A list of metrics is passed to train_autoencoder as a necessary parameter, default ones are within pipeline() and non-defaults can be passed to `pipeline` and added to the list.

Does this match what you had in mind?

**Comment by HoagyC** [comment]
Ok have drafted a PR to address this:
https://github.com/ai-safety-foundation/sparse_autoencoder/pull/64
