### ISSUE TITLE
Hot take: reduce linting requirements on PRs

### ISSUE THREAD

**Issue by ArthurConmy** [ai-safety-foundation/sparse_autoencoder#53]
I see two PRs currently with linting requirements. 

They seems like reasonable PRs, and IMO this is slowing down research. Running some linter on version `1.0.0` of this library when it is actually stable seems better to me than slowing stuff now

**Comment by alan-cooney** [comment]
Disabling linters/testing/typing is pretty universally a mistake in creating a lib, because it takes longer to develop (as you spend more time bug fixing) and the resulting code is less reliable. There isn't any trade off in speed/reliability once you get used to the tools. 

Anecdotally this is something that good engineers always seem to disagree with for a few years - I'm not really sure why - but for what it's worth if you ask essentially any staff engineer/above they'll agree (including in commercial research labs).

The exception is if you are experimenting with very small amounts of code, but we're getting close to standardising the abstractions now so I think we're past that. Also occasionally a specific rule causes unnecessary pain and in that case we can of course skip it.

Btw if you enable the default extensions for this repo in VSCode and (particularly ReWrap for the line length stuff), and then use the `poe` commands for auto-formatting, it should be extremely quick to fix any issues (and you will see it catching things you've missed regularly).

**Comment by ArthurConmy** [comment]
Thanks for the detailed disagreement! Glad this was a careful decision, happy to keep moving with this.
